package me.main.Kits;

public enum KitType {
  ANCHOR, AQUAMAN, ARCHER, CAMEL, ENDERMAGE, FIREMAN, FISHERMAN, FLASH, GLADIATOR, GLIDER, GRANDPA, GRAPPER, HERMIT, HULK, KANGAROO, MAGMA, NINJA, PHANTOM, POSEIDON, PYRO, PVP, REAPER, SNAIL, SPECIALIST, SPECTRE, STOMPER, SWITCHER, TANK, THOR, TURTLE, URGAL, VIKING, VIPER;
}